/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab01.richard.group04.a2;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.print("Do you want to register, login now or countinue as a guest?: ");
        Scanner scanner = new Scanner(System.in);
        String loginChoice = scanner.nextLine();
        while(true){
            
            if ("register".equalsIgnoreCase(loginChoice)) {
                    
                Registration.main(null);
                }
            else if ("login".equalsIgnoreCase(loginChoice)){
                UserLogin.main(null);
            }
            else if ("exit".equalsIgnoreCase(loginChoice)) {
                
                break;
            }
        }
        scanner.close();
    }
}
